# backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-course-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-course-app
  template:
    metadata:
      labels:
        app: student-course-app
    spec:
      containers:
      - name: student-course-app
        image: student-course-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: student-course-app
spec:
  type: NodePort
  selector:
    app: student-course-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
---
# frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-app-frontend
  template:
    metadata:
      labels:
        app: fullstack-app-frontend
    spec:
      containers:
      - name: fullstack-app-frontend
        image: fullstack-app-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-app-frontend
spec:
  type: NodePort
  selector:
    app: fullstack-app-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
