apiVersion: v1
kind: Service
metadata:
  name: fullstack-app-frontend-service
  namespace: monitoring
spec:
  selector:
    app: fullstack-app-frontend
  ports:
    - protocol: TCP
      port: 80        # external port
      targetPort: 3000 # container port React listens on
  type: NodePort
